spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/mato?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ?? ? update, ?? ? validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

  jwt:
    secret-key: ${SPRING_JWT_SECRET_KEY}

server:
  port: 8080
